build:
  type: composer

deploy:
  restart_php: true
  restart_webserver: true
  type: rsync

commands:
  build: |
    cd web/themes/custom/drupalbristol
    yarn --pure-lockfile
    node_modules/.bin/gulp --production
  deploy: |
    cd web
    drush -y cache-rebuild
    drush -y updatedb
    drush -y config-import
